yolo nas demo
tryolabs/norfair pull request #274
Opened 2023-08-14 19:16 UTC by agosl

Add a new demo using Yolo Nas as the object detector

2023-08-15 12:12 UTC, javiber requested changes
Great work! 
Just left some nitpicking and an idea to discuss in the group

2023-08-15 12:12 UTC, javiber commented on demos/yolo_nas/src/demo.py
> +import super_gradients
imports should be at the top, before the constants

2023-08-15 12:12 UTC, javiber commented on demos/yolo_nas/src/demo.py
> +def yolo_detections_to_norfair_detections(
Not something to implement in this PR but to think about and maybe add to the backlog

We've used this function so often that I believe it should be included in Norfair's utils. Maybe rename it to `xywh_detections_to_norfair` and call it with `yolo_detections.xywh`

2023-08-15 12:12 UTC, javiber commented on demos/yolo_nas/Dockerfile
> +RUN pip install super-gradients
we should the requirements from `requirements.txt` or remove the file

2023-08-15 12:12 UTC, javiber commented on demos/yolo_nas/requirements.txt
> +super-gradient==3.1.1
see comment above

2023-08-31 13:42 UTC, javiber approved these changes

2024-01-30 15:50 UTC, aguscas commented
Could we maybe add a mention of this demo in the main README.md? It could fit well in the [adding tracking to different detectors](https://github.com/tryolabs/norfair?tab=readme-ov-file#adding-tracking-to-different-detectors) section.

2024-01-30 16:05 UTC, aguscas commented
> Could we maybe add a mention of this demo in the main README.md? It could fit well in the [adding tracking to different detectors](https://github.com/tryolabs/norfair?tab=readme-ov-file#adding-tracking-to-different-detectors) section.

I just realize that we need to have It in the master first in order to provide a link to the demo from the main README, so forget whatever I said there.

2024-01-30 16:09 UTC, merged