Added labels to the drawing functions
tryolabs/norfair pull request #93
Opened 2022-03-08 12:45 UTC by facundo-lezama

Now that Norfair allows to track multiple objects from different classes within a single `Tracker` object, the modifications added in this PR make it possible to draw labels both on detections and tracked objects. It also adds the possibility to color points and bounding boxes based on the labels so that objects from the same class have the same color.

2022-03-08 13:02 UTC, facundo-lezama commented
These are some examples of how it looks when drawing bounding boxes:

<img width="637" alt="Screen Shot 2022-03-08 at 09 49 05" src="https://user-images.githubusercontent.com/92468171/157241505-02a99af8-602d-4110-b1d0-a7c8cae76c92.png">

<img width="640" alt="Screen Shot 2022-03-08 at 10 00 34" src="https://user-images.githubusercontent.com/92468171/157243046-eec38d74-1bf2-4221-ac50-4a899e93dcb3.png">

2022-03-09 18:31 UTC, joaqo requested changes
This is great! Almost ready to merge, just a couple of comments to discuss.

2022-03-09 18:31 UTC, joaqo commented on norfair/drawing.py
> +                f"Label: {d.label}",
"Label" string may occupy too much space when there are many objects on the image, it may make sense to make it shorter, or optional.

2022-03-09 18:31 UTC, joaqo commented on norfair/drawing.py
> +            lines_to_draw.append("label:{}".format(obj.label))
Probably better to abbreviate 'label', as it takes too much space on the image.

2022-03-11 17:44 UTC, joaqo commented on norfair/drawing.py
> +    draw_labels: Optional[bool] = False,
These don't need to be optional, as optional would effectively let this variable have 3 states (true, false, None) but we only need 2.

2022-03-11 17:44 UTC, joaqo commented on norfair/drawing.py
> +    draw_labels: Optional[bool] = False,
Same as above

2022-03-11 17:44 UTC, joaqo commented on norfair/drawing.py
> +    draw_labels: Optional[bool] = False,
Same

2022-03-11 18:41 UTC, merged