Add demo tracking keypoints and bounding boxes using OpenPose and YOLOv5
tryolabs/norfair pull request #99
Opened 2022-03-30 18:03 UTC by facundo-lezama

This PR builds a demo to show the possibilities that Norfair offers to track objects from multiple classes using a single `Tracker` instance. Also the example shows Norfair's ability to draw keypoints and bounding boxes for different types of objects.

2022-04-05 21:51 UTC, joaqo requested changes
This is great!

I left a few comments of things that may need changing. Also, we need to add a reference in the main README to this demo.

Finally, was wondering why the `production_ID_4791196_10s.mp4` file was versioned?

2022-04-05 21:51 UTC, joaqo commented on demos/keypoints_bounding_boxes/README.md
> +This example aims to show the possibilities that Norfair offers to track objects from multiple classes using a single `Tracker` instance. Also the example shows Norfair's ability to draw keypoints an
This example aims to show the possibilities -> This example aims at showing the possibilities

2022-04-05 21:51 UTC, joaqo commented on demos/keypoints_bounding_boxes/keypoints_bounding_boxes_demo.py
> +    return 1 / (1 + match_num)
Would be slightly more readable under an `else` statement, as we are choosing between 2 distinct options.

2022-04-05 21:51 UTC, joaqo commented on demos/keypoints_bounding_boxes/keypoints_bounding_boxes_demo.py
> +        for i, frame in enumerate(video):
I'd personally not support skipping frames in this demo. There are a lot of things going on, and we want to make each demo show off a small, easy to grasp, subset of Norfair's features. So anything that makes the demo shorter and simpler is better (except not tracking 2 classes 😂).

2022-04-05 21:53 UTC, joaqo commented
Just saw that that video is the input video for the demo. We should probably not version it, and store it somewhere so that users can download it manually. Maybe add a wget command to the demo or something like that.

2022-04-08 13:21 UTC, facundo-lezama commented
Made the requested changes. Regarding the input video I uploaded it by editing the README file from the web UI.

2022-04-08 17:51 UTC, merged